name: CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js 20.x
              uses: actions/setup-node@v4
              with:
                  node-version: 22.21.0
            - name: NPM Build and Test
              run: |
                  npm ci
                  npm run lint
                  npm run release
              env:
                  GITHUB_TOKEN: ${{ secrets.GHUB_BOT_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  DOCKER_USERNAME: fabulator
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
